package cli

import (
	"fmt"
	"net"

	"github.com/spf13/cobra"
)

// `odctl s3` — what to type into a backup program (§3.6.5).
//
// The keys are generated by the daemon on its first start and kept only in
// credentials.key; this, and the web page, are how a person reads them. It
// prints them because that is what it is for: somebody setting up Hyper Backup
// needs to copy them. It never writes them anywhere.

type s3Status struct {
	Enabled         bool   `json:"enabled"`
	Detail          string `json:"detail"`
	AccessKeyID     string `json:"access_key_id"`
	SecretAccessKey string `json:"secret_access_key"`
	HTTPSAddr       string `json:"https_addr"`
	HTTPAddr        string `json:"http_addr"`
	Fingerprint     string `json:"certificate_sha256"`
	CustomCert      bool   `json:"custom_certificate"`
	Delete          string `json:"delete"`
	Region          string `json:"region"`
}

func newS3Command(o *Options) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "s3",
		Short: "The S3 endpoint and key, for setting up backup software",
		Long: "Backup programs (Hyper Backup, restic, Kopia, Arq, Duplicati, rclone) talk to the\n" +
			"bridge over S3. This prints the address, access key and secret to give them.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			var st s3Status
			if err := client(o).Do(cmd.Context(), "GET", "/v1/s3", nil, &st); err != nil {
				return err
			}
			return printS3(o, st)
		},
	}
	cmd.AddCommand(&cobra.Command{
		Use:   "reset",
		Short: "Replace the S3 key; every client using the old one stops working",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			var st s3Status
			if err := client(o).Do(cmd.Context(), "POST", "/v1/s3/credentials/reset", nil, &st); err != nil {
				return err
			}
			if !o.JSON {
				_, _ = fmt.Fprintln(o.Out(), "New keys are in use. Give them to every program that used the old ones.")
				_, _ = fmt.Fprintln(o.Out())
			}
			return printS3(o, st)
		},
	})
	return cmd
}

func printS3(o *Options, st s3Status) error {
	if o.JSON {
		return printJSON(o, st)
	}
	out := o.Out()
	if !st.Enabled {
		_, _ = fmt.Fprintln(out, "The S3 gateway is off on this bridge.")
		if st.Detail != "" {
			_, _ = fmt.Fprintln(out, st.Detail)
		}
		return nil
	}
	endpoint := func(scheme, addr string) string {
		host, port, err := net.SplitHostPort(addr)
		if err != nil {
			return scheme + "://" + addr
		}
		if host == "" || host == "0.0.0.0" || host == "::" {
			host = "<this machine's address>"
		}
		return scheme + "://" + net.JoinHostPort(host, port)
	}
	if st.HTTPSAddr != "" {
		_, _ = fmt.Fprintf(out, "Endpoint (network):     %s\n", endpoint("https", st.HTTPSAddr))
	}
	if st.HTTPAddr != "" {
		_, _ = fmt.Fprintf(out, "Endpoint (this machine): %s\n", endpoint("http", st.HTTPAddr))
	}
	_, _ = fmt.Fprintf(out, "Access key:             %s\n", st.AccessKeyID)
	_, _ = fmt.Fprintf(out, "Secret key:             %s\n", st.SecretAccessKey)
	_, _ = fmt.Fprintf(out, "Region:                 %s (any is accepted)\n", st.Region)
	_, _ = fmt.Fprintln(out, "Addressing:             path style (not virtual-hosted)")
	_, _ = fmt.Fprintf(out, "Deletes go to:          %s\n", map[string]string{
		"trash": "OpenDrive's trash (recoverable)", "permanent": "nowhere (permanent)"}[st.Delete])
	if st.HTTPSAddr != "" && !st.CustomCert {
		_, _ = fmt.Fprintln(out)
		_, _ = fmt.Fprintln(out, "The HTTPS certificate is the bridge's own. When a program asks whether to")
		_, _ = fmt.Fprintln(out, "trust it, check its fingerprint is this one:")
		_, _ = fmt.Fprintf(out, "  SHA-256 %s\n", st.Fingerprint)
	}
	return nil
}
